In [1]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')

In [2]:
#defining the path
data_dir = Path("/Users/folasewaabdulsalam/Downloads/EEG_Based_Mental_Workload_Classifier/EEG-Based_Mental_Workload_Classifier/data")


In [3]:
#checking the structure of one text file
test_file = data_dir/'sub01_hi.txt'
sample_data = np.loadtxt(test_file)

print(f'The shape of the data is:{sample_data.shape}')
print(f'The data type is: {sample_data.dtype}')
print(f'\nThe first five rows and channels are:')
print(sample_data[:5, :5])

The shape of the data is:(19200, 14)
The data type is: float64

The first five rows and channels are:
[[4584.62 3902.05 4571.79 4589.23 4124.62]
 [4584.1  3895.9  4574.87 4567.69 4124.1 ]
 [4574.36 3893.85 4576.92 4572.82 4123.59]
 [4573.85 3906.15 4572.82 4612.31 4137.95]
 [4583.59 3911.28 4570.26 4621.03 4150.77]]


In [4]:
#defining the channel names with the Emotiv EPOC EEG channel names
channel_name = ['AF3', 'F7', 'F3', 'FC5', 'T7', 'P7', 'O1', 'O2', 'P8', 'T8', 'FC6', 'F4', 'F8', 'AF4']

In [ ]:
#visualizing the first 5 seconds of a channel
sampling_frequency = 128
duration = 5
no_of_samples = sampling_frequency * duration

time = np.arange(no_of_samples)/sampling_frequency

#plotting the first channel

